const SUPABASE_URL='https://uiyvzzuyjgbztijyxflb.supabase.co';
const SUPABASE_KEY='sb_publishable_qw6fTcjRikLZqzjQgDaBsg_EvGQgiU';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);

const MASECHTOT={
 'סנהדרין':{id:'sanhedrin',title:'מסכת סנהדרין',weeks:75,end:'דף קי״ג ע״ב'},
 'בבא קמא':{id:'bavakama',title:'מסכת בבא קמא',weeks:79,end:'דף קי״ט ע״ב'}
};
const WEEK_STARTS=['2026-10-11','2026-10-18','2026-10-25','2026-11-01','2026-11-08','2026-11-15','2026-11-22','2026-11-29','2026-12-06','2026-12-13','2026-12-20','2026-12-27','2027-01-03','2027-01-10','2027-01-17','2027-01-24','2027-01-31','2027-02-07','2027-02-14','2027-02-21','2027-02-28','2027-03-07','2027-03-14','2027-03-21','2027-03-28','2027-04-04','2027-05-09','2027-05-16','2027-05-23','2027-05-30','2027-06-06','2027-06-13','2027-06-20','2027-06-27','2027-07-04','2027-07-11','2027-07-18','2027-07-25','2027-08-01','2027-08-08','2027-08-15','2027-08-22','2027-08-29','2027-09-05','2027-09-12','2027-09-19','2027-09-26','2027-10-03','2027-10-10','2027-10-17','2027-10-24','2027-10-31','2027-11-07','2027-11-14','2027-11-21','2027-11-28','2027-12-05','2027-12-12','2027-12-19','2027-12-26','2028-01-02','2028-01-09','2028-01-16','2028-01-23','2028-01-30','2028-02-06','2028-02-13','2028-02-20','2028-02-27','2028-03-05','2028-03-12','2028-03-19','2028-03-26','2028-04-02','2028-04-09','2028-04-16','2028-04-23','2028-04-30','2028-05-07','2028-05-14','2028-05-21','2028-05-28','2028-06-04','2028-06-11','2028-06-18','2028-06-25','2028-07-02','2028-07-09','2028-07-16','2028-07-23','2028-07-30','2028-08-06','2028-08-13'];
let user=null,profile=null,currentMasechet='סנהדרין',currentIndex=0;

function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function rowsFor(m){return (window.DATA?.[m]||[])}
function studyRows(m){return rowsFor(m).filter(r=>r[4])}
function statusLabel(s){return s==='completed'?'✓ הושלם':s==='partial'?'◐ חלקי':'○ טרם הושלם'}
function statusClass(s){return s==='completed'?'completed':s==='partial'?'partial':'not_started'}
function weighted(rows,map){if(!rows.length)return 0;let n=0;rows.forEach(r=>{const s=map.get(r[0])||'not_started';n+=s==='completed'?1:s==='partial'?.5:0});return Math.round(n/rows.length*100)}
function getCurrentIndex(){const today=new Date().toISOString().slice(0,10);let idx=0;WEEK_STARTS.forEach((d,i)=>{if(d<=today)idx=i});return idx}
function go(view){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(view).classList.add('active');document.querySelectorAll('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.view===view));if(view==='personal')renderPersonal();if(view==='admin')renderAdmin()}
function renderHome(){
 const rows=rowsFor(currentMasechet),w=rows[currentIndex]||rows[0];
 document.getElementById('home').innerHTML=`<div class="hero-card"><div class="hero-kicker">קנין חכמה</div><h1>מסע של קנין</h1><p>תכנית מסודרת ללימוד מסכת סנהדרין ומסכת בבא קמא, עם מעקב אישי לכל אברך.</p></div><div class="section-head"><div><h2>השבוע הנוכחי</h2><p>ההספק המתוכנן והמעקב האישי במקום אחד.</p></div><button class="outline" id="personalQuick">האזור האישי</button></div>${currentWeekCard(w)}<div class="section-head"><div><h2>המסכתות</h2><p>בחר מסכת לצפייה בתכנית, בגרף ההתקדמות ובפרקים.</p></div></div><div class="masechet-cards">${Object.entries(MASECHTOT).map(([k,n])=>`<article class="masechet-card" data-m="${esc(k)}"><div class="gold-dot">✦</div><h3>${n.title}</h3><div class="meta">${n.weeks} שבועות לימוד · סיום ${n.end}</div><div class="card-link">לצפייה ומעקב ←</div></article>`).join('')}</div>`;
 document.getElementById('personalQuick').onclick=()=>go('personal');document.querySelectorAll('[data-m]').forEach(x=>x.onclick=()=>{currentMasechet=x.dataset.m;go('personal')});
}
function currentWeekCard(w){if(!w)return '<div class="card">אין נתונים.</div>';const active=!!w[4];return `<div class="card current-week"><div class="week-top"><span class="badge">${active?'השבוע הנוכחי':'בין הזמנים / ללא לימוד'}</span><strong>${esc(w[0])}</strong></div><h2>${esc(w[4]||'אין הספק לימוד השבוע')}</h2><div class="week-meta">${esc(w[1])} · פרשת ${esc(w[2]||'—')}</div><div class="week-info-grid"><div><small>מסכת</small><b>${esc(currentMasechet)}</b></div><div><small>פרק</small><b>${esc(w[5]||'—')}</b></div></div></div>`}
function renderPlan(){
 const rows=rowsFor(currentMasechet);const study=studyRows(currentMasechet);document.getElementById('plan').innerHTML=`<div class="section-hero"><span>תכנית הלימוד</span><h2>${MASECHTOT[currentMasechet].title}</h2><p>${MASECHTOT[currentMasechet].weeks} שבועות לימוד · סיום ${MASECHTOT[currentMasechet].end}</p></div><div class="card chooser"><label>בחר מסכת</label><div class="switches">${Object.keys(MASECHTOT).map(k=>`<button class="switch ${k===currentMasechet?'selected':''}" data-switch="${esc(k)}">${esc(MASECHTOT[k].title)}</button>`).join('')}</div></div><div class="card"><h3>גרף התקדמות כללי</h3><div id="generalChart"></div></div><div class="card"><h3>התקדמות לפי פרק</h3><div id="perekChart"></div></div><div class="card table-card"><h3>לוח השבועות</h3><div class="table-scroll"><table><thead><tr><th>שבוע</th><th>תאריכים</th><th>פרשה</th><th>הספק</th><th>פרק</th></tr></thead><tbody>${rows.map((r,i)=>`<tr class="${i===currentIndex?'current-row':''}"><td>${esc(r[0])}</td><td>${esc(r[1])}</td><td>${esc(r[2]||'—')}</td><td class="hespek">${esc(r[4]||'—')}</td><td>${esc(r[5]||'—')}</td></tr>`).join('')}</tbody></table></div></div>`;
 document.querySelectorAll('[data-switch]').forEach(b=>b.onclick=()=>{currentMasechet=b.dataset.switch;renderPlan();renderPersonal()});renderPlanCharts(currentMasechet,study);
}
async function progressMap(m){if(!user)return new Map();const {data,error}=await sb.from('kch_weekly_progress').select('week_no,status').eq('user_id',user.id).eq('masechet',m);if(error)throw error;return new Map((data||[]).map(x=>[Number(x.week_no),x.status]));}
async function renderPlanCharts(m,study){const general=document.getElementById('generalChart'),perek=document.getElementById('perekChart');if(!user){general.innerHTML='<div class="login-hint">התחבר לאזור האישי כדי לראות את ההתקדמות שלך.</div>';perek.innerHTML='';return}const map=await progressMap(m);const pct=weighted(study,new Map(study.map(r=>[r[0],map.get(Number(r[0].split(' ').pop()))||'not_started'])));const done=study.filter(r=>map.get(Number(r[0].split(' ').pop()))==='completed').length;general.innerHTML=`<div class="big-percent">${pct}%</div><div class="bar"><i style="width:${pct}%"></i></div><div class="meta">${done} מתוך ${study.length} שבועות הושלמו</div>`;const groups={};study.forEach(r=>{(groups[r[5]||'ללא פרק']??=[]).push(r)});perek.innerHTML=Object.entries(groups).map(([p,arr])=>{const pp=weighted(arr,new Map(arr.map(r=>[r[0],map.get(Number(r[0].split(' ').pop()))||'not_started'])));return `<div class="perek-line"><div><b>${esc(p)}</b><span>${pp}%</span></div><div class="bar small"><i style="width:${pp}%"></i></div><small>${arr.length} שבועות</small></div>`}).join('')}
function authHtml(){return `<div class="card auth-card"><div class="auth-head"><div class="gold-dot">◈</div><div><h2>אזור אישי</h2><p>לכל אברך חשבון אישי והתקדמות פרטית.</p></div></div><div class="auth-grid"><div><h3>כניסה</h3><label>אימייל</label><input id="loginEmail" type="email"><label>סיסמה</label><input id="loginPassword" type="password"><button class="primary" id="loginBtn">כניסה</button></div><div class="signup"><h3>יצירת משתמש חדש</h3><label>שם מלא</label><input id="signupName"><label>אימייל</label><input id="signupEmail" type="email"><label>סיסמה</label><input id="signupPassword" type="password"><button class="secondary" id="signupBtn">יצירת חשבון</button></div></div><div id="authMsg"></div></div>`}
async function renderPersonal(){const root=document.getElementById('personal');if(!user){root.innerHTML=authHtml();bindAuth();return}const rows=studyRows(currentMasechet);let map=await progressMap(currentMasechet);const statuses=new Map(rows.map(r=>[Number(r[0].split(' ').pop()),map.get(Number(r[0].split(' ').pop()))||'not_started']));const pct=weighted(rows,new Map(rows.map(r=>[r[0],statuses.get(Number(r[0].split(' ').pop()))])));const w=rowsFor(currentMasechet)[currentIndex];const currentStatus=w&&w[4]?statuses.get(Number(w[0].split(' ').pop())):'not_started';const allStats={};for(const m of Object.keys(MASECHTOT)){const sr=studyRows(m),pm=await progressMap(m);allStats[m]=weighted(sr,new Map(sr.map(r=>[r[0],pm.get(Number(r[0].split(' ').pop()))||'not_started'])))}root.innerHTML=`<div class="section-hero"><span>האזור האישי</span><h2>שלום, ${esc(profile?.full_name||user.email)}</h2><p>המעקב שלך נשמר בחשבון האישי וגלוי לך ולמנהל החבורה.</p></div><div class="card profile-card"><div><b>${esc(profile?.full_name||'')}</b><div class="meta">${profile?.role==='admin'?'מנהל החבורה':'אברך'}</div></div><button class="outline" id="logoutBtn">יציאה</button></div><div class="stat-grid"><div class="stat"><small>סנהדרין</small><strong>${allStats['סנהדרין']}%</strong></div><div class="stat"><small>בבא קמא</small><strong>${allStats['בבא קמא']}%</strong></div><div class="stat"><small>מסכת נבחרת</small><strong>${pct}%</strong></div></div><div class="card"><div class="section-head"><div><h3>התקדמות כללית — ${esc(currentMasechet)}</h3><p>${MASECHTOT[currentMasechet].weeks} שבועות לימוד</p></div></div><div class="big-percent">${pct}%</div><div class="bar"><i style="width:${pct}%"></i></div></div>${weekProgressCard(w,currentStatus)}<div class="card"><h3>התקדמות לפי פרק</h3><div id="personalPerek"></div></div><div class="card"><h3>שבועות קודמים</h3><p class="meta">אפשר לעדכן גם שבועות שכבר עברו.</p><div class="makeup-list" id="makeupList"></div></div>`;
document.getElementById('logoutBtn').onclick=async()=>{await sb.auth.signOut();await refreshSession();renderPersonal();renderHome()};renderPersonalPerek(rows,statuses);renderMakeup(rows,statuses);}
function weekProgressCard(w,s){if(!w||!w[4])return '<div class="card current-progress disabled"><span class="badge">אין לימוד השבוע</span><h3>אין הספק לעדכון</h3><p class="meta">זהו שבוע בין הזמנים או שבוע ללא לימוד.</p></div>';return `<div class="card current-progress"><span class="badge">${esc(w[0])} · השבוע הנוכחי</span><h3>${esc(w[4])}</h3><p class="meta">${esc(w[1])} · ${esc(w[5])}</p><div class="status-buttons"><button class="status ${s==='completed'?'chosen':''}" data-current-status="completed">✓ הושלם</button><button class="status ${s==='partial'?'chosen':''}" data-current-status="partial">◐ חלקי</button><button class="status ${s==='not_started'?'chosen':''}" data-current-status="not_started">○ טרם הושלם</button></div><div id="saveMsg" class="save-msg">${statusLabel(s)}</div></div>`}
async function saveStatus(weekNo,status,masechet=currentMasechet){if(!user)return;const {error}=await sb.from('kch_weekly_progress').upsert({user_id:user.id,masechet,week_no:Number(weekNo),status},{onConflict:'user_id,masechet,week_no'});if(error){alert('שגיאה בשמירה: '+error.message);return}await renderPersonal();await renderHome();if(document.getElementById('plan').classList.contains('active'))renderPlan();}
function renderPersonalPerek(rows,statuses){const groups={};rows.forEach(r=>(groups[r[5]||'ללא פרק']??=[]).push(r));document.getElementById('personalPerek').innerHTML=Object.entries(groups).map(([p,a])=>{const pp=weighted(a,new Map(a.map(r=>[r[0],statuses.get(Number(r[0].split(' ').pop()))])));return `<div class="perek-line"><div><b>${esc(p)}</b><span>${pp}%</span></div><div class="bar small"><i style="width:${pp}%"></i></div><small>${a.length} שבועות</small></div>`}).join('');document.querySelectorAll('[data-current-status]').forEach(b=>b.onclick=()=>{const w=rowsFor(currentMasechet)[currentIndex];if(w?.[4])saveStatus(Number(w[0].split(' ').pop()),b.dataset.currentStatus)});}
function renderMakeup(rows,statuses){const previous=rowsFor(currentMasechet).slice(0,currentIndex).filter(r=>r[4]);const box=document.getElementById('makeupList');box.innerHTML=previous.slice(-12).reverse().map(r=>{const no=Number(r[0].split(' ').pop()),s=statuses.get(no)||'not_started';return `<div class="makeup"><div><b>${esc(r[0])}</b><span>${esc(r[4])}</span></div><div class="mini-status ${statusClass(s)}">${statusLabel(s)}</div><div class="makeup-buttons"><button data-makeup="${no}" data-s="completed">✓</button><button data-makeup="${no}" data-s="partial">◐</button><button data-makeup="${no}" data-s="not_started">○</button></div></div>`}).join('')||'<div class="meta">אין שבועות קודמים להשלמה.</div>';box.querySelectorAll('[data-makeup]').forEach(b=>b.onclick=()=>saveStatus(b.dataset.makup,b.dataset.s));}
function bindAuth(){document.getElementById('loginBtn').onclick=async()=>{const email=loginEmail.value.trim(),password=loginPassword.value;if(!email||!password)return authMessage('יש למלא אימייל וסיסמה',true);authMessage('מתחבר…');const {error}=await sb.auth.signInWithPassword({email,password});if(error)return authMessage(error.message,true);await refreshSession();renderPersonal();renderHome()};document.getElementById('signupBtn').onclick=async()=>{const name=signupName.value.trim(),email=signupEmail.value.trim(),password=signupPassword.value;if(!name||!email||!password)return authMessage('יש למלא את כל השדות',true);if(password.length<6)return authMessage('הסיסמה חייבת להכיל לפחות 6 תווים',true);authMessage('יוצר חשבון…');const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)return authMessage(error.message,true);if(data.session){await refreshSession();renderPersonal();renderHome()}else authMessage('החשבון נוצר. אם נדרש, אשר את האימייל ואז היכנס.');}}
function authMessage(t,e=false){const x=document.getElementById('authMsg');x.textContent=t;x.className=e?'error':'success'}
async function refreshSession(){const {data:{user:u}}=await sb.auth.getUser();user=u||null;profile=null;if(user){const {data}=await sb.from('kch_profiles').select('*').eq('id',user.id).maybeSingle();profile=data||null}document.getElementById('adminNav').classList.toggle('hidden',profile?.role!=='admin')}
async function renderAdmin(){
 const root=document.getElementById('admin');
 if(profile?.role!=='admin'){root.innerHTML='<div class="card"><h2>ניהול</h2><p class="error">הגישה מיועדת למנהל החבורה בלבד.</p></div>';return}
 const [{data:members,error:merr},{data:progress,error:perr}]=await Promise.all([sb.from('kch_profiles').select('id,full_name,role,created_at').order('full_name'),sb.from('kch_weekly_progress').select('user_id,masechet,week_no,status')]);
 if(merr||perr){root.innerHTML='<div class="card error">לא ניתן לטעון את נתוני הניהול.</div>';return}
 const ms=members||[],pr=progress||[],admins=ms.filter(x=>x.role==='admin').length,active=ms.filter(m=>pr.some(p=>p.user_id===m.id)).length;
 const calcMember=(id,masechet)=>{const sr=studyRows(masechet),mp=new Map(pr.filter(x=>x.user_id===id&&x.masechet===masechet).map(x=>[Number(x.week_no),x.status]));const score=sr.reduce((n,r)=>n+(mp.get(Number(r[0].split(' ').pop()))==='completed'?1:mp.get(Number(r[0].split(' ').pop()))==='partial'?.5:0),0);return {pct:sr.length?Math.round(score/sr.length*100):0,map:mp,study:sr}};
 const average=masechet=>ms.length?Math.round(ms.reduce((n,u)=>n+calcMember(u.id,masechet).pct,0)/ms.length):0;
 const groupStats=masechet=>{let done=0,partial=0,pending=0,total=0;ms.forEach(u=>{const d=calcMember(u.id,masechet);d.study.forEach(r=>{total++;const s=d.map.get(Number(r[0].split(' ').pop()))||'not_started';if(s==='completed')done++;else if(s==='partial')partial++;else pending++})});return {done,partial,pending,total}};
 const statusChip=s=>`<span class="mini-status ${statusClass(s)}">${statusLabel(s)}</span>`;
 const cards=ms.map(u=>{const a=calcMember(u.id,'סנהדרין'),b=calcMember(u.id,'בבא קמא'),curS=rowsFor('סנהדרין')[currentIndex],curB=rowsFor('בבא קמא')[currentIndex],ss=curS?.[4]?a.map.get(Number(curS[0].split(' ').pop()))||'not_started':'not_started',bs=curB?.[4]?b.map.get(Number(curB[0].split(' ').pop()))||'not_started':'not_started';return `<article class="admin-member-card" data-member="${u.id}"><div class="admin-member-top"><div><h3>${esc(u.full_name||'ללא שם')}${u.role==='admin'?' <span title="מנהל">👑</span>':''}</h3><small>${u.role==='admin'?'מנהל החבורה':'אברך'}</small></div><button class="outline member-detail" data-member="${u.id}">פתיחת תיק ←</button></div><div class="admin-progress-grid"><div><div><b>סנהדרין</b><strong>${a.pct}%</strong></div><div class="bar"><i style="width:${a.pct}%"></i></div></div><div><div><b>בבא קמא</b><strong>${b.pct}%</strong></div><div class="bar"><i style="width:${b.pct}%"></i></div></div></div><div class="admin-current"><span>השבוע</span><span>סנהדרין ${statusChip(ss)}</span><span>בבא קמא ${statusChip(bs)}</span></div></article>`}).join('');
 const renderDistribution=masechet=>{const x=groupStats(masechet),d=x.total?Math.round(x.done/x.total*100):0,pa=x.total?Math.round(x.partial/x.total*100):0,pe=x.total?100-d-pa:0;return `<div class="dist-wrap"><div class="dist-bar"><i style="width:${d}%"></i><i style="width:${pa}%"></i><i style="width:${pe}%"></i></div><div class="dist-legend"><span><b class="dot done-dot"></b>הושלם ${d}%</span><span><b class="dot partial-dot"></b>חלקי ${pa}%</span><span><b class="dot pending-dot"></b>טרם הושלם ${pe}%</span></div></div>`};
 root.innerHTML=`<div class="section-hero admin"><span>ניהול</span><h2>לוח הבקרה של החבורה</h2><p>תמונה מלאה של ההתקדמות, מצב השבוע ופירוט אישי של כל אברך.</p></div>${admins===0?'<div class="card first-admin"><h3>הגדרת מנהל ראשון</h3><p class="meta">אם עדיין אין מנהל, המשתמש הראשון יכול לתפוס את תפקיד המנהל.</p><button class="primary" id="claimAdmin">הגדר אותי כמנהל</button></div>':''}<div class="admin-stats"><div><small>אברכים</small><b>${ms.length}</b><span>רשומים במערכת</span></div><div><small>פעילים</small><b>${active}</b><span>כבר סימנו התקדמות</span></div><div><small>סנהדרין — ממוצע</small><b>${average('סנהדרין')}%</b><span>ממוצע החבורה</span></div><div><small>בבא קמא — ממוצע</small><b>${average('בבא קמא')}%</b><span>ממוצע החבורה</span></div></div><div class="admin-chart-grid"><div class="card"><div class="admin-card-head"><div><h3>התקדמות כללית של החבורה</h3><p class="meta">ממוצע אישי של כל האברכים</p></div></div><div class="group-chart"><div><label>סנהדרין <b>${average('סנהדרין')}%</b></label><div class="bar big"><i style="width:${average('סנהדרין')}%"></i></div></div><div><label>בבא קמא <b>${average('בבא קמא')}%</b></label><div class="bar big"><i style="width:${average('בבא קמא')}%"></i></div></div></div></div><div class="card"><div class="admin-card-head"><div><h3>מצב ביצוע שבועי</h3><p class="meta">כל סימוני ההתקדמות שנרשמו</p></div></div><h4 style="margin:8px 0 4px">סנהדרין</h4>${renderDistribution('סנהדרין')}<h4 style="margin:18px 0 4px">בבא קמא</h4>${renderDistribution('בבא קמא')}</div></div><div class="section-head admin-list-head"><div><h2>האברכים</h2><p>לחץ על אברך כדי לפתוח את התיק המלא שלו.</p></div><span class="badge">${ms.length} משתמשים</span></div><div class="admin-members">${cards||'<div class="card empty">אין משתמשים.</div>'}</div><div id="memberDetail"></div>`;
 if(document.getElementById('claimAdmin'))document.getElementById('claimAdmin').onclick=async()=>{const {data,error}=await sb.rpc('kch_claim_first_admin');if(error||!data)return alert('לא ניתן להגדיר מנהל ראשון.');await refreshSession();renderAdmin()};root.querySelectorAll('.member-detail').forEach(b=>b.onclick=()=>showMemberDetail(b.dataset.member,ms,pr));
}
function showMemberDetail(id,ms,pr){
 const u=ms.find(x=>x.id===id);if(!u)return;const masechtot=Object.keys(MASECHTOT);
 const makeData=masechet=>{const sr=studyRows(masechet),mp=new Map(pr.filter(x=>x.user_id===id&&x.masechet===masechet).map(x=>[Number(x.week_no),x.status]));const score=sr.reduce((n,r)=>n+(mp.get(Number(r[0].split(' ').pop()))==='completed'?1:mp.get(Number(r[0].split(' ').pop()))==='partial'?.5:0),0);const pct=sr.length?Math.round(score/sr.length*100):0;const groups={};sr.forEach(r=>(groups[r[5]||'ללא פרק']??=[]).push(r));return {sr,mp,pct,groups}};
 const datasets=Object.fromEntries(masechtot.map(m=>[m,makeData(m)]));
 const overall=masechtot.map(m=>`<div class="member-detail-stat"><small>${esc(m)}</small><b>${datasets[m].pct}%</b><div class="bar"><i style="width:${datasets[m].pct}%"></i></div></div>`).join('');
 const perek=m=>Object.entries(datasets[m].groups).map(([p,a])=>{const score=a.reduce((n,r)=>n+(datasets[m].mp.get(Number(r[0].split(' ').pop()))==='completed'?1:datasets[m].mp.get(Number(r[0].split(' ').pop()))==='partial'?.5:0),0),x=a.length?Math.round(score/a.length*100):0;return `<div class="perek-line"><div><b>${esc(p)}</b><span>${x}%</span></div><div class="bar"><i style="width:${x}%"></i></div><small>${a.length} שבועות לימוד</small></div>`}).join('');
 const weekly=m=>datasets[m].sr.map(r=>{const n=Number(r[0].split(' ').pop()),s=datasets[m].mp.get(n)||'not_started';return `<div class="admin-week-row"><span class="week-no">${esc(r[0])}</span><span class="week-hespek">${esc(r[4])}</span>${statusChip(s)}</div>`}).join('');
 const detail=document.getElementById('memberDetail');detail.innerHTML=`<div class="card detail-card admin-detail-card"><div class="detail-top"><div><span class="badge">תיק אישי</span><h2>${esc(u.full_name||'ללא שם')}${u.role==='admin'?' 👑':''}</h2><p class="meta">${u.role==='admin'?'מנהל החבורה':'אברך'}</p></div><button class="outline" id="closeDetail">סגירת פירוט</button></div><div class="member-detail-stats">${overall}</div><div class="detail-switches"><button class="switch selected" data-detail-m="סנהדרין">סנהדרין</button><button class="switch" data-detail-m="בבא קמא">בבא קמא</button></div><div id="memberDetailBody"><div class="detail-two-col"><div><h3>התקדמות לפי פרק</h3>${perek('סנהדרין')}</div><div><h3>התקדמות שבועית</h3><div class="admin-week-list">${weekly('סנהדרין')}</div></div></div></div></div>`;
 const body=document.getElementById('memberDetailBody');rootDetailSwitches(detail,body,datasets,perek,weekly);document.getElementById('closeDetail').onclick=()=>{detail.innerHTML='';window.scrollTo({top:0,behavior:'smooth'})};detail.scrollIntoView({behavior:'smooth',block:'start'});
}
function rootDetailSwitches(detail,body,datasets,perek,weekly){detail.querySelectorAll('[data-detail-m]').forEach(b=>b.onclick=()=>{detail.querySelectorAll('[data-detail-m]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const m=b.dataset.detailM;body.innerHTML=`<div class="detail-two-col"><div><h3>התקדמות לפי פרק</h3>${perek(m)}</div><div><h3>התקדמות שבועית</h3><div class="admin-week-list">${weekly(m)}</div></div></div>`})}
function renderPlanOrHome(){renderHome();renderPlan()}
sb.auth.onAuthStateChange(()=>setTimeout(async()=>{await refreshSession();if(document.getElementById('personal').classList.contains('active'))renderPersonal();renderHome()},0));
window.addEventListener('kinyan-data-ready',()=>{currentIndex=getCurrentIndex();renderPlanOrHome();renderPersonal();refreshSession()});
